### ISSUE TITLE
Feature Request: configurable precision for export to InfluxDB

### ISSUE THREAD

**Issue by dpajin** [openconfig/gnmic#17]
Current configuration assumes `ns` precision when writing to InfluxDB. However, if the "override ts" processor is used with the different precision, for example `s`, this will result with wrong timestamps in InfluxDB, because seconds are passed as nanoseconds.

The ideal would be having a configurable option for timestamp precision for export to InfluxDB and normalization of the event timestamp before passing it to the influxdb client library.

**Comment by karimra** [comment]
I see two ways to achieve this use case:
1) 
- Adding a knob under influxDB output that sets the desired write precision. 
- The timestamp override should be done by the influxDB output (`override-timestamps: true`) and not by the `override-ts` processor.
Meaning that influxDB output will still assume that the TS in the received messages is in `ns` and converts it based on the configured precision before writing (and overrides the TS if configured). 
A limitation if this is implement is that the `override-ts` can only be used with an influxDB output if it overrides to `ns` precision.

2)
- Adding two knobs under influxDB output, `expected-ts-precision` and `write-ts-precision`
- The output will be aware of the received TS precision and converts/writes accordingly.

I prefer the first option since it will be easier to implement and it achieves the desired use case.
@dpajin  Let me know what you think.

**Comment by dpajin** [comment]
I agree with you about the option 1, it should be good enough
