### ISSUE TITLE
Service flappiness when using clustering?

### ISSUE THREAD

**Issue by smiller-dn** [openconfig/gnmic#207]
Hi.  We're using clustering to hand targets out to individual `gnmic` instances, and looking at the Consul API and the logs, we see a lot of flapping with the service registrations.  TBH it's not 100% clear that it causes problems, but it seems disturbing enough that we've been trying to track it down.

We have a three-pod Consul cluster running in EKS.  That's defined as a k8s service -- I might be getting the terminology wrong here -- such that `consul-server.consul.svc.cluster.local` resolves to three IP addresses, each of which corresponds to one of the Consul agents that are members of the cluster.

The TTL on those A records is only 5 seconds.  The A records in the DNS response seem to be rotated, so at any given moment, any of the three IPs will be the first on the list.

And we have a three-node (or six-node, in our production environment) `gnmic` cluster, whose `clustering` config looks like:

```
  clustering:
    locker:
      type: consul
      address: consul-server.consul.svc.cluster.local:8500
```

The individual `gnmic` pods aren't running the Consul proxy sidecar, though from other experiments it seems like that wouldn't help: it's not shortcutting the connections from each `gnmic` pod to a constant Consul IP address.  `k8s exec` ing into a pod using the proxy, then doing::

```
wget -d -O - http://consul-consul-server.consul.svc:8500/v1/agent/host | python3 -m json.tool - | grep hostname
```

gives us back different hostnames, so we are clearly ending up talking to different Consul instances (and there's also clearly no port on the sidecar to which we should be sending, the only thing there is a DNS server that can send faked-up responses to certain hostnames... but which isn't queried by the system resolver).

You can watch the `dc1-gnmic-api` service in the Consul UI Services view, and we'll see multiple instances of the service registered at the same time, listing different Consul servers, where there's one healthy instance and often at least one unhealthy instance, such as:

<img width="1587" alt="consul-service-wackiness" src="https://github.com/openconfig/gnmic/assets/129762804/d0f7327a-95f8-439f-83f1-8d9dd211fe5a">

We've tried adjusting the `locker` timeouts, e.g.:

```
      session-ttl: 60s
      delay: 5s
      retry-timer: 2s
      renew-period: 10s
```

but that doesn't help.

There's a hardcoded `5s` `DeregisterCriticalServiceAfter` value in [consul_registration.go](./lockers/consul_locker/consul_registration.go), and we've tried upping that to `60s`, with or without the `locker` timeout changes above, and that doesn't help, we still see the flappiness.  Given that Consul logs things like:

```
2023-08-18T14:42:16.535Z [WARN]  agent: check has deregister interval below minimum: check=service:gnmic-ss-2-api minimum_interval=1m0s
```

it seemed like maybe the Consul internal syncing stuff wasn't reacting fast enough, hence the bump to `60s`.  But no luck.

Based on a toooon of tcpdumping, what I think is happening is:

   - `gnmic` instance 0 uses the Consul API to get a new connection to Consul; to open that connection, it resolves `consul-server.consul.svc.cluster.local`, and the Consul API (or `Dial`)  chooses the first A record in the list; we'll say that's 1.2.3.4
   - `gnmic` uses the new Consul API connection to register the `gnmic-ss-0-api` service instance on the Consul server at 1.2.3.4
   - there's a goroutine that periodically wakes up and sends a keepalive, to keep the service instance registered
   - sometimes, for whatever reason, the API will decide to open another connection, which is likely to be to a different Consul service given the A-record randomization
   - if the API connects to a different one, say, 5.6.7.8, it sends a keepalive, which is rejected by 5.6.7.8, because that Consul server doesn't know about that instance
      - at which point the API and/or `gnmic` itself sees the error and re-registers the service instance on 5.6.7.8
      - and eventually the instance registration on 1.2.3.4 times out and goes away and we go back down to having a single `gnmic-ss-0-api` service instance in the Consul UI

If we nuke our three-node Consul cluster and replace it with a single-node cluster, we don't get the flappiness at all; we see a rare missed TTL message in Consul, like:

```
2023-08-18T14:42:21.536Z [WARN]  agent: Check missed TTL, is now critical: check=service:gnmic-ss-0-api
```

but that's quite rare, and certainly a lot more rare than what we see with the three-node Consul cluster.

The whole deregistration, from Consul's standpoint, looks something like:

```
# from Consul pod 0
2023-08-23T00:19:59.335Z [WARN]  agent: Check missed TTL, is now critical: check=service:gnmic-ss-1-api
2023-08-23T00:19:59.343Z [INFO]  agent: Synced check: check=service:gnmic-ss-1-api
2023-08-23T00:21:06.860Z [INFO]  agent: Synced check: check=service:gnmic-ss-1-api
2023-08-23T00:21:11.854Z [WARN]  agent: Check missed TTL, is now critical: check=service:gnmic-ss-1-api
2023-08-23T00:21:11.858Z [INFO]  agent: Synced check: check=service:gnmic-ss-1-api
2023-08-23T00:22:24.316Z [INFO]  agent: deregistered service with critical health due to exceeding health check's 'deregister_critical_service_after' timeout: service=gnmic-ss-1-api check=service:gnmic-ss-1-api timeout=1m0s # 5s, with the default hard-coded deregistration interval
2023-08-23T00:22:24.320Z [INFO]  agent: Deregistered service: service=gnmic-ss-1-api
2023-08-23T00:25:49.353Z [ERROR] agent.http: Request error: method=PUT url=/v1/agent/check/update/service:gnmic-ss-1-api from=10.144.18.75:33164 error="Unknown check ID \"service:gnmic-ss-1-api\". Ensure that the check ID is passed, not the check name."
2023-08-23T00:25:59.367Z [INFO]  agent: Synced service: service=gnmic-ss-1-api
2023-08-23T00:25:59.372Z [INFO]  agent: Synced check: check=service:gnmic-ss-1-api

# from Consul pod 1
2023-08-23T00:18:11.954Z [INFO]  agent: Deregistered service: service=gnmic-ss-1-api
2023-08-23T00:18:11.954Z [INFO]  agent: deregistered service with critical health due to exceeding health check's 'deregister_critical_service_after' timeout: service=gnmic-ss-1-api check=service:gnmic-ss-1-api timeout=1m0s
2023-08-23T00:19:56.834Z [ERROR] agent.http: Request error: method=PUT url=/v1/agent/check/update/service:gnmic-ss-1-api from=10.144.18.75:44118 error="Unknown check ID \"service:gnmic-ss-1-api\". Ensure that the check ID is passed, not the check name."
2023-08-23T00:20:06.846Z [INFO]  agent: Synced service: service=gnmic-ss-1-api
2023-08-23T00:20:06.852Z [INFO]  agent: Synced check: check=service:gnmic-ss-1-api
2023-08-23T00:25:51.856Z [WARN]  agent: Check missed TTL, is now critical: check=service:gnmic-ss-1-api
2023-08-23T00:25:51.862Z [INFO]  agent: Synced check: check=service:gnmic-ss-1-api

# Consul pod 2 had no pertinent messages at around the right time
```

So, I'm not sure if:
   - we've done something broken with our Consul cluster
   - we've done something broken with how we talk to Consul, e.g.:
      - the DNS responses should always present the IPs in the same order depending on the source of the query
      - there's some way to list, say, the individual pod hostnames, so the API knows they're three separate instances
      - we should be having each `gnmic` instance talk to its own Consul agent (which then somehow joins the Consul cluster?)
      - the Consul proxy sidecar will make this magically better despite what our similar-but-not-identical testing says
    - we're the first people to try to run with `replicas` > 1 in our Consul cluster
    - everyone runs `gnmic` in EC2 or somesuch, and has a Consul agent running on each `gnmic` instance
    - it just looks like this for everyone and we happened to notice and we shouldn't be worrying our pretty little heads

Have you seen something like this before?

(Also: if there's a mailing list or a slack channel or somesuch that I should be using, rather than opening issues, please let me know!)

Thanks for any insight you can offer.

**Comment by karimra** [comment]
Thanks for the detailed issue description.

You don't have to run a Consul agent as a side car with every gNMIc instance.

You have to deploy a cluster of Consul servers as a **StatefulSet** (3 or 5 servers) and Consul clients as a **DaemonSet** (one per k8s node).

Each gNMIc instance should register with its local (running on the same k8s node) Consul client which will forward that registration to the Consul servers cluster (StatefulSet) where the consensus mechanism happens and the actual data is stored.

With the official [Consul Helm chart](https://developer.hashicorp.com/consul/docs/k8s/helm) the distinction between clients and servers is already made for you. The Helm chart deploys Consul clients as a DaemonSet and Consul servers as a StatefulSet with the appropriate configurations.

In summary:

1. Consul Clients (DaemonSet):

- Deployed on every node in the Kubernetes cluster.
- Do not store long-term data; they forward requests to Consul servers.
- Local applications connect to the local Consul client agent.

2. Consul Servers (StatefulSet):

- Deployed as a fixed number, often 3 or 5 nodes for high availability.
- Responsible for the Raft consensus and storing the actual data.
- These nodes communicate with each other to maintain consistency and replicate data.

The Consul architecture and terminology can be a bit confusing so I added the definitions of the terms `agent`, `server` and `client`. 


**Agent** - An agent is the long running daemon on every member of the Consul cluster. It is started by running consul agent. **_The agent is able to run in either client or server mode_**. Since all nodes must be running an agent, it is simpler to refer to the node as being either a client or server, but there are other instances of the agent. All agents can run the DNS or HTTP interfaces, and are responsible for running checks and keeping services in sync.

**Client** - A client is an agent that forwards all RPCs to a server. The client is relatively stateless. The only background activity a client performs is taking part in the LAN gossip pool. This has a minimal resource overhead and consumes only a small amount of network bandwidth.

**Server** - A server is an agent with an expanded set of responsibilities including participating in the Raft quorum, maintaining cluster state, responding to RPC queries, exchanging WAN gossip with other datacenters, and forwarding queries to leaders or remote datacenters.

In short, an agent can be either a server or a client. The server is stateful while the client is stateless. 
A service can register directly with a Consul server in simple deployments. In a k8s cluster is it recommended to follow the StatefulSet and DaemonSet deployments described above.

(There is a [discord channel](https://discord.com/channels/860500297297821756/1039586757408202802) under the containerlab discord server where you can ask gnmic related questions if you don't want to open issues here)

**Comment by smiller-dn** [comment]
Thanks -- after a few false starts, we have this running in a dev environment now, and expect to deploy to prod soon.

The trick is that in whatever values being passed into the helm chart for consul, one should say:

```
consul:
  client:
    enabled: true
```

at which point the Consul helm chart will take care of creating the right DaemonSet.

Then on the gnmic side, you can do something like this in the StatefulSet definition:

```
spec:
  template:
    spec:
      containers:
        - args:
           env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: GNMIC_CLUSTERING_LOCKER_ADDRESS
              value: "$(HOST_IP):8500"
```

(maybe modulo a bit of copy/paste-related formatting errors) and gnmic will pull the locker address from the environment on startup, and it'll connect to the consul client on the node as expected.

In other news, on the off-chance that anyone ever reads this again, note that as of this writing the kubernetes support in Docker Desktop (for Mac, at least) doesn't seem to support working access to `hostPort` definitions on the node IP.  That is, if `${HOST_IP}` is 1.2.3.4, and there's a `hostPort` definition for 8500/tcp, you can try to connect to http://1.2.3.4:8500 all you want, but you won't get a working connection.  However, doing the same thing in AWS EKS works just fine, as I found after hours of banging my head against that particular wall... 😄 I didn't try it in minikube.

**Comment by smiller-dn** [comment]
Thanks -- after a few false starts, we have this running in a dev environment now, and expect to deploy to prod soon.

The trick is that in whatever values being passed into the helm chart for consul, one should say:

```
consul:
  client:
    enabled: true
```

at which point the Consul helm chart will take care of creating the right DaemonSet.

Then on the gnmic side, you can do something like this in the StatefulSet definition:

```
spec:
  template:
    spec:
      containers:
        - args:
           env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: GNMIC_CLUSTERING_LOCKER_ADDRESS
              value: "$(HOST_IP):8500"
```

(maybe modulo a bit of copy/paste-related formatting errors) and gnmic will pull the locker address from the environment on startup, and it'll connect to the consul client on the node as expected.

In other news, on the off-chance that anyone ever reads this again, note that as of this writing the kubernetes support in Docker Desktop (for Mac, at least) doesn't seem to support working access to `hostPort` definitions on the node IP.  That is, if `${HOST_IP}` is 1.2.3.4, and there's a `hostPort` definition for 8500/tcp, you can try to connect to http://1.2.3.4:8500 all you want, but you won't get a working connection.  However, doing the same thing in AWS EKS works just fine, as I found after hours of banging my head against that particular wall... 😄 I didn't try it in minikube.
