### ISSUE TITLE
Is it possible to add tags to the JSON output format?

### ISSUE THREAD

**Issue by AhmedNSidd** [openconfig/gnmic#43]
My requirement is as follows: 

I am able to successfully receive telemetry metrics from a router using gNMIc but I would like to be able to add tags to the JSON output so that I can add a tag to signify what the `interface_name` is for the metric I just received. I realize that the `event` output format does that for me automatically, but the client that's getting the data needs the schema to be in the format that's outputted by the `json` output format. 

It seems like my only option under these conditions is to use Processors to convert the model schema of my telemetry data from the `event` schema to something that looks closer to the `json` schema. Is this my only option? Or is there a way to add tags to a `json` output format? 

Thank you.

**Comment by karimra** [comment]
Indeed there is no way to add tags to the json output format. The event format is supposed to be used for that.
Since you are receiving the metric together with the full path(including the key name) you can already link the metric with the interface name (same is valid for the event format BTW)

I'm wondering which client ingest gNMIc's json format? That format is specific to this tool and was intended to be used for terminal output and readability.

**Comment by AhmedNSidd** [comment]
Makes sense. Actually, I say client, but what I really mean is that the upper levels of my team were using the schema with the JSON output format, and I was making sure that there was no alternative aside from switching to the event format, which we are going to do now thanks to your help. Anyway, I'll close the issue now. Again, thanks for your help.
