### ISSUE TITLE
stringArray in the main branch is not working as expected

### ISSUE THREAD

**Issue by rao-aneesh** [openconfig/gnmic#479]
A Get request created like this:
```
gnmic --address x.x.x.x --port 57400 --username xxx --password xxx --insecure get --path openconfig-system:system/state/hostname,openconfig-system:system/state/boot-time --type ALL --encoding JSON_IETF --print-request --format prototext
```

Generates this RPC:

Get Request:
```
path:  {
  elem:  {
    name:  "openconfig-system:system"
  }
  elem:  {
    name:  "state"
  }
  elem:  {
    name:  "hostname,openconfig-system:system"
  }
  elem:  {
    name:  "state"
  }
  elem:  {
    name:  "boot-time"
  }
}
encoding:  JSON_IETF
```

Comma separated string arrays are supported in 0.37.0. Did something change?

**Comment by karimra** [comment]
I'm planning to deprecate that behavior (comma separated paths). The only flag that will support comma separated values will be `-a | --address`

**Comment by rao-aneesh** [comment]
Alright. Any reason why?

**Comment by karimra** [comment]
The same behavior can be achieved using multiple --path flags, which I find cleaner than using comma-separated paths. Parsing comma-separated paths is error-prone since paths can contain commas (in the key value), forcing the user to escape commas. This makes the feature (comma-separated paths) tedious to use.

**Comment by rao-aneesh** [comment]
Okay, thanks!
